server:
  listen: ":8080"
  dataDir: "/data"
  repoCacheDir: "/data/repos"
auth:
  mode: dev-no-auth
  agent:
    tokenEnv: GITOPS_DASHBOARD_AGENT_TOKEN
monitoring:
  defaultInterval: 30s
repositories: []
runtime:
  docker:
    - name: compose-docker-agent
      kind: agent
      agentTokenEnv: GITOPS_DASHBOARD_AGENT_TOKEN
  http:
    - name: routes
      interval: 1m
      timeout: 5s
  kubernetes: []
  ping: []
